import type { SignalType } from './types/market';
import type { AppSettings } from './types/settings';

export const ENGINE_CONFIG = {
  liquidationCascadeWindowMs: 10_000,
  liquidationCascadeUsd: 500_000,
  liquidationClusterCount: 5,
  liquidationClusterWindowMs: 30_000,
  volumeSurgeMultiplier: 3,
  priceMovePercent: 0.008,
  rangeBreakWindowMs: 4_000,
  rangeBreakBufferPercent: 0.00015,
  learningFilterSamples: 15,
  learningFilterWinRate: 0.35,
  learningBoostConfidence: 0.6,
  maxSignals: 50,
  maxSignalHistory: 500,
  maxLiquidations: 500,
  maxVerificationHistory: 1_000,
  openInterestRefreshMs: 45_000,
  openInterestTopSymbols: 12,
  publishThrottleMs: 200,
  staleFeedMs: 8_000,
  retention: {
    priceMs: 60_000,
    volumeMs: 60_000,
    liquidationMs: 3_600_000,
    tradeMs: 60_000,
    cvdMs: 60_000,
    flowMs: 30_000,
  },
  ttlMs: {
    WHALE_FLUSH_REVERSAL: 180_000,
    CASCADE_CONTINUATION: 120_000,
    ABSORPTION_SETUP: 300_000,
    BREAKOUT_CONFIRMED: 90_000,
    MOMENTUM_SURGE: 60_000,
    FLOW_REVERSAL_LONG: 90_000,
    FLOW_REVERSAL_SHORT: 90_000,
    FUND_SQUEEZE_LONG: 600_000,
    FUND_SQUEEZE_SHORT: 600_000,
    OI_CONFIRM_LONG: 120_000,
    OI_CONFIRM_SHORT: 120_000,
    OI_SQUEEZE: 300_000,
  } satisfies Record<SignalType, number>,
} as const;

export const DEFAULT_SETTINGS: AppSettings = {
  toastEnabled: true,
  toastSound: true,
  ttsEnabled: true,
  vibrate: false,
  toastPosition: 'br',
  toastDurationSeconds: 9,
  toastTiers: ['S', 'A'],
  toastMinScore: 55,

  minLiquidationUsd: 10_000,
  whaleBaseUsd: 300_000,
  maxLiquidationUsd: 0,
  liquidationTicker: true,
  liquidationTickerWhalesOnly: false,
  liquidationTickerSpeedSeconds: 30,
  coinglassEnabled: false,
  coinglassExchanges: ['Binance'],
  aggTradeFollowSeconds: 90,

  minSignalScore: 35,
  signalTiers: ['S', 'A', 'B'],
  signalCooldownSeconds: 60,
  signalFamilies: ['WHALE', 'CASCADE', 'ABSORPTION', 'BREAKOUT', 'MOMENTUM', 'FLOW', 'OI', 'FUND'],
  autoOpenTradingView: false,
  autoOpenBinance: false,
  min24hVolumeUsd: 5_000_000,
  maxPositionPercent: 15,
  roundTripCostBps: 8,

  theme: 'candy',
  animations: true,
  compactMode: false,
  mobileNavigation: true,
  language: 'tr',
  absoluteTime: false,
  moneyFormat: 'short',

  autoReconnect: true,
  debugWebSocket: false,
  maxAggTradeSymbols: 10,
  symbolWhitelist: '',
  symbolBlacklist: '',
  fundingThresholdPercent: 0.01,

  learningEnabled: true,
  autoVerify: true,
  adaptiveVerifyHorizon: true,
  fallbackVerifyMinutes: 5,
  minimumLearningSamples: 10,
};

export const APP_VERSION = '3.0.0';
export const STORAGE_VERSION = 3;
